### ISSUE TITLE
Add Namespace info

### ISSUE THREAD

**Issue by JeremyParish69** [cosmos/wallet-registry#9]
With the recent launch of ICNS, namespace is on mind.

We could have an object property just for namespaces?
```
...
"namespaces": {
  "icns": true,
  "starname": false,
  "stargaze's namespace": false
},
...
```

Or each namespace could be an allowed keyword within 'features'?
```
...
"features": [
  "suggest-chain",
  "icns",
  "starname-namespace"
],
...
```

**Comment by pyramation** [comment]
let's keep it in `features`, seems good to me.
